"""added user.role

Revision ID: 8d0d92f30a30
Revises: 
Create Date: 2020-12-23 02:02:02.342625

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d0d92f30a30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('role', sa.Enum('average', 'master', name='roleenum'), nullable=True),
    sa.Column('password_hash', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advertisements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(length=50), nullable=True),
    sa.Column('description', mysql.TINYTEXT(), nullable=True),
    sa.Column('topic', sa.String(length=15), nullable=True),
    sa.Column('modifier', sa.Enum('public', 'local', name='modifierenum'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advertisements')
    op.drop_table('users')
    # ### end Alembic commands ###
